name: Build Docker Images
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/pac_docker
      - name: Build and release Docker images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/386,linux/amd64,linux/arm64/v8
          tags: ${{ steps.metadata.outputs.tags }}
          push: true